# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Patrick McCarthy
tagline:          A blog
url:              http://ptmccarthy.github.io
paginate:         1
baseurl:          /
author:
  name:           Patrick McCarthy
  url:            https://twitter.com/ptmccarthy
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
